# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    "name": "Nepali IRD Api Integrations",
    "version": "18.0",
    "summary": "Nepali IRD Integration",
    "description": "Nepali VAT System",
    "category": "Accounting",
    "author": "Smarten Technologies Pvt. Ltd.",
    "website": "https:smarten.com.np",
    "license": "AGPL-3",
    "data": [
        "reports/paper_format.xml",
        "reports/pos_ird_report.xml",
        "wizards/salesbook_wizard.xml",
        "views/sales_book.xml",
        # 'view/sale_order_line.xml',
        "views/res_cmpny.xml",
        # 'data/data.xml',
        "security/ir.model.access.csv",
        "views/menu.xml",
        "views/purchase_book.xml",
        "views/sales_return.xml",
        "views/purchase_tds.xml",
        "views/purchase_return.xml",
        "views/sales_book_annex13.xml",
        "views/purchase_book_annex13.xml",
        "reports/ird_report.xml",
        "views/views.xml",
        "views/account_move_templates.xml",
        "data/report_paperformat_data.xml",
        "views/audit_log_report.xml",
        "views/account_move.xml",
        # 'wizards/annex_vat_tds_report.xml',
    ],
    "assets": {
        "web.assets_backend": [
            # 'nepali_ird_integration/static/src/services/*.js',
        ],
    },
    "depends": [
        "base",
        "sale_management",
        "account",
        "accountant",
        "l10n_np",
        "auditlog",
        "global_discount",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
